### ISSUE TITLE
SpikeSortingError Error

### ISSUE THREAD

**Issue by elduvelle** [elduvelle/SpikeinterfaceMS4_GenzelLab#9]
```
Num. workers = 8
Preparing C:\Users\Eleonore\AppData\Local\Temp\tmpn79s_tnl/timeseries.hdf5...
Preparing neighborhood sorters (M=4, N=371439416)...
Cleaning tmpdir:: C:\Users\Eleonore\AppData\Local\Temp\tmpn79s_tnl
Error running mountainsort4
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\spikeinterface\sorters\basesorter.py", line 200, in run_from_folder
    SorterClass._run_from_folder(output_folder, sorter_params, verbose)
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\spikeinterface\sorters\mountainsort4\mountainsort4.py", line 116, in _run_from_folder
    old_api_sorting = mountainsort4.mountainsort4(
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\mountainsort4\mountainsort4.py", line 38, in mountainsort4
    MS4.sort()
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\mountainsort4\ms4alg.py", line 842, in sort
    dask.compute(*dask_list, num_workers=self._num_workers)
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\dask\base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\dask\multiprocessing.py", line 232, in get
    result = get_async(
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\dask\local.py", line 497, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

Traceback (most recent call last):
  File "C:\Users\Eleonore\Documents\GitHub\SpikeinterfaceMS4_GenzelLab\ScriptMS4_ED.py", line 557, in <module>
    mda_params, ms_sort_params, multisession)
  File "C:\Users\Eleonore\Documents\GitHub\SpikeinterfaceMS4_GenzelLab\ScriptMS4_ED.py", line 282, in run_MS_on_folder
    concat_figs_fold = os.path.join(concat_fold, 'sample_figures')
  File "C:\Users\Eleonore\Documents\GitHub\SpikeinterfaceMS4_GenzelLab\ScriptMS4_ED.py", line 124, in run_Mountainsort
    sorting_MS = ss.run_mountainsort4(recording,
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\spikeinterface\sorters\runsorter.py", line 419, in run_mountainsort4
    return run_sorter('mountainsort4', *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\spikeinterface\sorters\runsorter.py", line 67, in run_sorter
    return run_sorter_local(sorter_name, recording, output_folder=output_folder,
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\spikeinterface\sorters\runsorter.py", line 89, in run_sorter_local
    SorterClass.run_from_folder(output_folder, raise_error, verbose)
  File "C:\ProgramData\Anaconda3\envs\MoutainSort_Phy_test\lib\site-packages\spikeinterface\sorters\basesorter.py", line 236, in run_from_folder
    raise SpikeSortingError(
spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in D:\DATA\exp1_modal_maze\r208_ephys\2024-04-13\r208_a_spm8-1_concat_13\output_T26\results_MS/spikeinterface_log.json

```

**Comment by elduvelle** [comment]
I reran it and it worked
